### ISSUE TITLE
switch flows local copy can easily get outdated

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/flow_stats#19]
Since flow_stats is keeping its own copy of `switch.flows` (https://github.com/kytos-ng/flow_stats/blob/master/main.py#L530-L559), it can easily get outdated when new changes are requested to flow_manager and until the next flow_stats is received.

We should review the actually need for keeping a local copy of flows, or find a way to update our local copy upon new changes on flow_manager (very difficult and will possibly incur duplicate efforts with flow_manager).

One possible impact is sdntrace_cp returining invalid traces.

**Comment by viniarck** [comment]
Great point, @italovalcy. When the time comes, It might be worth considering either a new MongoDB collection joining (`$lookup`) with the current `flows` (filling the gaps with stats related stuff) or augment that one (and/or expose new endpoints when reading from it), if it's not going to store a time series like.
