### ISSUE TITLE
Update code badges on README.md

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/flow_stats#45]
`flow_stats` is being stabilized, it should have similar badges that [`flow_manager`](https://raw.githubusercontent.com/kytos-ng/flow_manager/master/README.rst) and other stable NApps have:

```
|Stable| |Tag| |License| |Build| |Coverage| |Quality|
```

We'll need this for the release notes. @gretelliz could you help out with this?

**Comment by gretelliz** [comment]
Sure! @viniarck
