### ISSUE TITLE
feat: Create a new napp `kytos_stats` from `flow_stats`

### ISSUE THREAD

**Issue by gretelliz** [kytos-ng/flow_stats#53]
This is related to [EP035](https://github.com/kytos-ng/kytos/blob/master/docs/blueprints/EP035.rst)

This napp will evolve to `kytos_stats` for kytos statistics, including OF table stats support.

- To build `kytos_stats`, one forking from `flow_stats` will be created and then, this napp will be depreciated.
- An equivalent behavior of flow stats to the current one in `flow_stats` will be kept.
- The napp will subscribe to the `kytos/of_core.table_stats.received` event,
- A data structure will be updated with this event and will be indexed by `dpid` and `table_id`. 
-  An API endpoint will be added to get the statistics of tables and will be provided query parameters filtering by `dpid` and optionally by `table_id`.
```
GET v1/table/stats 

{
  "dpid_1": {
    0: {"table_id": 0, "active_count": a0, "lookup_count": b0, "matched_count": c0}
    1: {"table_id": 1, "active_count": a1, "lookup_count": b1, "matched_count": c1}
    ...
    n: {"table_id": n, "active_count": an, "lookup_count": bn, "matched_count": cn}
  },
  ...
  "dpid_n": {
    ...
  }
}
```
-Unit test will be updated.

**Comment by viniarck** [comment]
@gretelliz can this be closed since `kytos/kytos_stats` has been created or do you need to cover anything else here?
